services:
  postgres:
    image: postgres:18
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin4:
    image: dpage/pgadmin4:9.14.0
    profiles: ["tools"]
    restart: no
    env_file: 
      - .env
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres

volumes:
  pg18_data: