services:
  postgres:
    image: postgres:18
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg18_data:/var/lib/postgresql

  pgadmin4:
    image: dpage/pgadmin4:9.14.0
    profiles: ["tools"]
    restart: no
    env_file: 
      - .env
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - backend_media:${FILE_PREFIX}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg18_data:
  backend_media:
